### Pandas: Work with lines! [Homework]
> ** You must import all the necessary packages yourself. **

> ** Write the code only where it is shown for recording. Do not delete comments! **


### Step 1

Please write the function `` `Load_Data (Filename)` ``, which will download data from the CSV file to the list of lists. Please write the function `` Load_Data (Filename) `` `, which will download data from the CSV file to` `Dataframe``` '. The file is `` num_house_Prices.csv`` 'provided with this Jupyter Notebook.


**Note:**

* If the file name is defined incorrectly, the function is `` Load_Data`` 'The following error message should display:

```{имя файла} does not exist```
* ```str_house_prices.csv``` - это csv-файл, который является результатом вашей предыдущей домашней работы.

In [8]:
os.listdir()

['dirty_str_house_prices.csv',
 'HW_1_nlp.ipynb',
 '.git',
 'clean_house_prices.csv',
 'Social_Network_Ads.csv']

In [10]:
os.path.exists(filename)

False

In [11]:
#Начало вашего кода
import pandas as pd
import os.path
import csv 
#load_data() function that downloads data from the csv file to the list of lists 
def load_data(filename):
        pd_data = [] 
        if not os.path.exists(filename):
                print('./SocialNetworkAds.csv does not exist')
                return None
        else:
                with open(filename, 'r') as file: 
                        reader = csv.reader(file) 
                        for row in reader: 
                                pd_data.append(row) 
                print(type(pd_data))
                return pd_data
#Конец вашего кода

In [12]:
filename = "./SocialNetworkAds.csv"
data1 = load_data(filename)

./SocialNetworkAds.csv does not exist


### Ожидаемый результат:

```
./SocialNetworkAds.csv does not exist
```

In [13]:
print(data1)

None


### Ожидаемый результат:

```
None
```

In [20]:
import pandas as pd

def load_data_1(filename):
    # Load and drop saved index column
    df = pd.read_csv(filename, index_col=0)   
    return df 
     
filename = "./clean_house_prices.csv"
data = load_data_1(filename)

In [19]:
data

[['Id',
  'MSSubClass',
  'MSZoning',
  'LotArea',
  'Street',
  'LotShape',
  'LandContour',
  'Utilities',
  'LotConfig',
  'LandSlope',
  'Neighborhood',
  'Condition1',
  'Condition2',
  'BldgType',
  'HouseStyle',
  'OverallQual',
  'OverallCond',
  'YearBuilt',
  'YearRemodAdd',
  'RoofStyle',
  'RoofMatl',
  'Exterior1st',
  'Exterior2nd',
  'MasVnrType',
  'MasVnrArea',
  'ExterQual',
  'ExterCond',
  'Foundation',
  'BsmtQual',
  'BsmtCond',
  'BsmtExposure',
  'BsmtFinType1',
  'BsmtFinSF1',
  'BsmtFinType2',
  'BsmtFinSF2',
  'BsmtUnfSF',
  'TotalBsmtSF',
  'Heating',
  'HeatingQC',
  'CentralAir',
  'Electrical',
  '1stFlrSF',
  '2ndFlrSF',
  'LowQualFinSF',
  'GrLivArea',
  'BsmtFullBath',
  'BsmtHalfBath',
  'FullBath',
  'HalfBath',
  'BedroomAbvGr',
  'KitchenAbvGr',
  'KitchenQual',
  'TotRmsAbvGrd',
  'Functional',
  'Fireplaces',
  'GarageType',
  'GarageYrBlt',
  'GarageFinish',
  'GarageCars',
  'GarageArea',
  'GarageQual',
  'GarageCond',
  'PavedDrive',
  'WoodD

In [21]:
print(data.columns.values.tolist()) 

['MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondi

### Ожидаемый результат:

```
['Id', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']
```

In [ ]:
""" 
the clean csv file provided has more values than the dirty csv  
so in step 1 we need to get the clean version to compare it to the cleaned dirty one in step 4 
so i didnt really understand why the expected result here is of the dirty data set values 
and not the clean ones 
""" 

In [ ]:
data 

Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0        1       RL   Pave      Reg         LVL    Allpub    Inside       GTL   
1        2       RL   Pave      Reg         LVL    Allpub       FR2       GTL   
2        3       RL   Pave      IR1         LVL    Allpub    Inside       GTL   
3        4       RL   Pave      IR1         LVL    Allpub    Corner       GTL   
4        5       RL   Pave      IR1         LVL    Allpub       FR2       GTL   
...    ...      ...    ...      ...         ...       ...       ...       ...   
1333  1456       RL   Pave      Reg         LVL    Allpub    Inside       GTL   
1334  1457       RL   Pave      Reg         LVL    Allpub    Inside       GTL   
1335  1458       RL   Pave      Reg         LVL    Allpub    Inside       GTL   
1336  1459       RL   Pave      Reg         LVL    Allpub    Inside       GTL   
1337  1460       RL   Pave      Reg         LVL    Allpub    Inside       GTL   

     Neighborhood Condition1  ... Electrical KitchenQual Functional  \
0         Collgcr       Norm  ...      Sbrkr          GD        TYP   
1         Veenker      Feedr  ...      Sbrkr          TA        TYP   
2         Collgcr       Norm  ...      Sbrkr          GD        TYP   
3         Crawfor       Norm  ...      Sbrkr          GD        TYP   
4         Noridge       Norm  ...      Sbrkr          GD        TYP   
...           ...        ...  ...        ...         ...        ...   
1333      Gilbert       Norm  ...      Sbrkr          TA        TYP   
1334       Nwames       Norm  ...      Sbrkr          TA       Min1   
1335      Crawfor       Norm  ...      Sbrkr          GD        TYP   
1336        Names       Norm  ...      Fusea          GD        TYP   
1337      Edwards       Norm  ...      Sbrkr          TA        TYP   

     GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
0        Attchd          RFN         TA         TA          Y       WD   
1        Attchd          RFN         TA         TA          Y       WD   
2        Attchd          RFN         TA         TA          Y       WD   
3        Detchd          UNF         TA         TA          Y       WD   
4        Attchd          RFN         TA         TA          Y       WD   
...         ...          ...        ...        ...        ...      ...   
1333     Attchd          RFN         TA         TA          Y       WD   
1334     Attchd          UNF         TA         TA          Y       WD   
1335     Attchd          RFN         TA         TA          Y       WD   
1336     Attchd          UNF         TA         TA          Y       WD   
1337     Attchd          FIN         TA         TA          Y       WD   

     SaleCondition  
0           Normal  
1           Normal  
2           Normal  
3          Abnorml  
4           Normal  
...            ...  
1333        Normal  
1334        Normal  
1335        Normal  
1336        Normal  
1337        Normal  

[1338 rows x 39 columns]

**Распечатайте первые и последние 5 строк pandas.DataFrame:**

In [ ]:
#Начало вашего кода
print(data.head())
print(data.tail())
#Конец вашего кода

    MSSubClass MSZoning  LotArea Street LotShape LandContour Utilities  \
Id                                                                       
1           60       RL     8450   Pave      Reg         Lvl    AllPub   
2           20       RL     9600   Pave      Reg         Lvl    AllPub   
3           60       RL    11250   Pave      IR1         Lvl    AllPub   
4           70       RL     9550   Pave      IR1         Lvl    AllPub   
5           60       RL    14260   Pave      IR1         Lvl    AllPub   

   LotConfig LandSlope Neighborhood  ... EnclosedPorch 3SsnPorch ScreenPorch  \
Id                                   ...                                       
1     Inside       Gtl      CollgCr  ...             0         0           0   
2        FR2       Gtl      Veenker  ...             0         0           0   
3     Inside       Gtl      CollgCr  ...             0         0           0   
4     Corner       Gtl      Crawfor  ...           272         0           0   
5

###  Expected results:

```
Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0   1       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1   2       RL   Pave      Reg         Lvl    AllPub       FR2       Gtl
2   3       RL   Pave      IR1         Lvl    AllPub    Inside       Gtl
3   4       RL   Pave      IR1         Lvl    AllPub    Corner       Gtl
4   5       RL   Pave      IR1         Lvl    AllPub       FR2       Gtl

Neighborhood Condition1  ... Electrical KitchenQual Functional GarageType  \
0      CollgCr       Norm  ...      SBrkr          Gd        Typ     Attchd
1 Veenker Feed R ... SCRKR TA PAY CHECKED
2      CollgCr       Norm  ...      SBrkr          Gd        Typ     Attchd
3      Crawfor       Norm  ...      SBrkr          Gd        Typ     Detchd
4      NoRidge       Norm  ...      SBrkr          Gd        Typ     Attchd

GarageFinish GarageQual GarageCond PavedDrive SaleType SaleCondition
0 RFn NOT WA
1 RFn Normal WD
2 RFn NOT WA
3 UNF TA TA Y WD ABNORML
44 RFn NOT WA

[5 rows x 39 columns]
Id MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
1333  1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1334  1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1335  1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1336  1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl
1337  1460       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl

Neighborhood Condition1  ... Electrical KitchenQual Functional  \
1333 Gilbert Norm ... Sbrkr take type
1334 NWAMES NORM ... SBRKR TA Min1
1335      Crawfor       Norm  ...      SBrkr          Gd        Typ
1336        NAmes       Norm  ...      FuseA          Gd        Typ
1337 Edwards norm ... SBRK TAKE TYPE

GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
1333 Atchd RFn RFn THE WD
1334 Attchd Unf THE WD
1335 Attchd RFn RFn THE WD
1336 Atchd Unf THE WD
1337 Atchd Fin THE WD

Salecondition
1333        Normal
1334        Normal
1335        Normal
1336        Normal
1337        Normal

[5 rows x 39 columns]
```

### Step 2

Run the code block below and try to get some insight into the data you are looking at.

In [ ]:
pd_data=data.copy()
#pd_data.reset_index(inplace=True) 

Please implement a ```count_by_group(data,column)``` function that returns statistics by group ```column``` for column ```column``` in a ```DataFrame```. The statistics contain the number of unique values ​​in the column.

In [ ]:
#Начало вашего кода
def count_by_group(data,column):
    counts = {} 
    for value in data[column]: 
        if value in counts: 
            counts[value] += 1 
        else: 
            counts[value] = 1 
    data1 = pd.Series(counts, name=column)
    data1 = data1.sort_index()
    return data1
#Конец вашего кода

def count_by_group1(data,column):
    counts = {} 
    for value in data[column]: 
        if value in counts: 
            counts[value] += 1 
        else: 
            counts[value] = 1 
    data1 = pd.Series(counts, name=column)
    data1 = data1.sort_values(ascending=False)
    return data1

In [ ]:
data.groupby('LotShape').count()

MSSubClass  MSZoning  LotArea  Street  LandContour  Utilities  \
LotShape                                                                  
IR1              459       459      459     459          459        459   
IR2               40        40       40      40           40         40   
IR3               10        10       10      10           10         10   
Lvl                1         1        1       0            1          1   
Reg              828       828      828     828          828        828   

          LotConfig  LandSlope  Neighborhood  Condition1  ...  EnclosedPorch  \
LotShape                                                  ...                  
IR1             459        459           459         459  ...            459   
IR2              40         40            40          40  ...             40   
IR3              10         10            10          10  ...             10   
Lvl               1          1             1           1  ...              1   
Reg             828        828           828         828  ...            828   

          3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
LotShape                                                                        
IR1             459          459       459      459     459     459       459   
IR2              40           40        40       40      40      40        40   
IR3              10           10        10       10      10      10        10   
Lvl               1            1         1        1       1       1         1   
Reg             828          828       828      828     828     828       828   

          SaleCondition  SalePrice  
LotShape                            
IR1                 459        459  
IR2                  40         40  
IR3                  10         10  
Lvl                   1          0  
Reg                 828        828  

[5 rows x 73 columns]

In [ ]:
result=count_by_group(data=pd_data,column="LotShape")
print("Lotter", "\n", result)

Lotter 
 IR1    459
IR2     40
IR3     10
Lvl      1
Reg    828
Name: LotShape, dtype: int64


### Ожидаемый результат:

```
Lotter
IR1 459
IR2     40
IR3     10
Reg    829
Name: LotShape, dtype: int64
```

In [ ]:
results = {col: count_by_group1(pd_data, col)
           for col in pd_data.select_dtypes(include="object").columns} 
print(type(results)) # class "dict" 
print(results) 

<class 'dict'>
{'MSZoning': RL         1066
RM          191
FV           62
RH           11
C (all)       8
Name: MSZoning, dtype: int64, 'Street': Pave    1332
Grvl       5
NaN        1
Name: Street, dtype: int64, 'LotShape': Reg    828
IR1    459
IR2     40
IR3     10
Lvl      1
Name: LotShape, dtype: int64, 'LandContour': Lvl       1205
Bnk         52
HLS         48
Low         32
AllPub       1
Name: LandContour, dtype: int64, 'Utilities': AllPub    1336
NoSeWa       1
Inside       1
Name: Utilities, dtype: int64, 'LotConfig': Inside     956
Corner     244
CulDSac     90
FR2         43
FR3          4
Gtl          1
Name: LotConfig, dtype: int64, 'LandSlope': Gtl        1264
Mod          61
Sev          12
Edwards       1
Name: LandSlope, dtype: int64, 'Neighborhood': NAmes      209
CollgCr    146
OldTown    100
Somerst     83
Gilbert     77
NridgHt     75
NWAmes      73
Sawyer      69
Edwards     69
SawyerW     53
Crawfor     50
BrkSide     47
Mitchel     42
NoRidge     41
Timber  

###  Expected results:

```
<class 'dict'>
{'MSZoning': RL         1066
RM          191
FV           62
RH           11
C (all)       8
Name: MSZoning, dtype: int64, 'Street': Pave    1333
Grvl       5
Name: Street, dtype: int64, 'LotShape': Reg    829
IR1 459
IR2     40
IR3     10
Name: LotShape, dtype: int64, 'LandContour': Lvl    1206
BNK 52
HLS      48
Low      32
Name: LandContour, dtype: int64, 'Utilities': AllPub    1337
Nome avoid 1
Name: Utilities, dtype: int64, 'LotConfig': Inside     957
Corner     244
CulDSac     90
43 difference
Fr3 4
Name: LotConfig, dtype: int64, 'LandSlope': Gtl    1265
Mod      61
Sev      12
Name: LandSlope, dtype: int64, 'Neighborhood': NAmes      209
Collgcr 146
Oldtown 100
Somerst     83
Gilbert     77
NridgHt     75
The baby 73
Edwards     70
Sawyer      69
SawyerW     53
Crawfor     50
Brxide 47
Mitchel     42
NoRidge     41
Timber      37
Idotrr 29
ClearCr     26
StoneBr     25
Swisu 20
Blmngtn     17
Brdale 15
MeadowV     12
Veenker 11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64, 'Condition1': Norm      1162
Feedr       63
Artery      43
RRAN 26
Poson 19
Rrae 10
Put 8
Rrn 5
RRNe         2
Name: Condition1, dtype: int64, 'Condition2': Norm      1324
Feedr        5
Artery       2
Poson 2
Rrn 2
Put 1
IRRAN 1
Rrae 1
Name: Condition2, dtype: int64, 'BldgType': 1Fam      1138
Tunhse 112
Tunhs 38
Duplex      28
2fmCon      22
Name: BldgType, dtype: int64, 'HouseStyle': 1Story    657
2Story    426
1.5pen 134
SLvl       64
SFOYER 30
1.5Unf     11
2.5Unf     10
2.5Fin 6
Name: HouseStyle, dtype: int64, 'RoofStyle': Gable      1037
Hip         272
Flat         11
Gambrel      10
Mansard 6
Shed          2
Name: RoofStyle, dtype: int64, 'RoofMatl': CompShg    1314
Tar & GRR9
Wdshngl 6
WdShake       5
Roll          1
Membrane 1
ClyTile       1
Metal         1
Name: RoofMatl, dtype: int64, 'Exterior1st': VinylSd    486
HdBoard    211
MetalSd    201
WD SDNG 183
Plywood    100
Cemntbd 52
BrkFace     44
Stucco 21
WdShing     20
AsbShng     15
Stone        2
Shimasta 1
BrkComm      1
CBlock       1
Name: Exterior1st, dtype: int64, 'Exterior2nd': VinylSd    475
MetalSd    197
HdBoard    197
WD SDNG 176
Plywood    127
CmentBd     51
Wd Shng     32
Stucco 23
BrkFace     22
AsbShng     16
Shimastak 10
Brk Cmn      6
AsphShn      2
Stone        2
CBlock       1
Other        1
Name: Exterior2nd, dtype: int64, 'MasVnrType': None       763
BrkFace    432
Stone      128
Brkcmn 15
Name: MasVnrType, dtype: int64, 'ExterQual': TA    803
Gd    477
Ex     51
Fa      7
Name: ExterQual, dtype: int64, 'ExterCond': TA    1183
Gd     137
Fa      16
Ex       2
Name: ExterCond, dtype: int64, 'Foundation': PConc     620
CBlock    580
On the Brk 129
Stone       6
Wood        3
Name: Foundation, dtype: int64, 'BsmtQual': TA    594
Gd    592
Ex    120
Fa     32
Name: BsmtQual, dtype: int64, 'BsmtCond': TA    1237
Gd      62
Fa      38
After 1
Name: BsmtCond, dtype: int64, 'BsmtExposure': No    887
Of 213
Gd    127
Mn    111
Name: BsmtExposure, dtype: int64, 'BsmtFinType1': GLQ    402
Unf    392
Alq 209
Fir 141
Rec    125
LWQ 69
Name: BsmtFinType1, dtype: int64, 'BsmtFinType2': Unf    1176
Rec      53
Lwq 46
Fir 32
Alq 19
GLQ      12
Name: BsmtFinType2, dtype: int64, 'Heating': GasA    1318
Neat 16
Grav       3
OTH 1
Name: Heating, dtype: int64, 'HeatingQC': Ex    704
By 380
Gd    217
Fa     36
After 1
Name: HeatingQC, dtype: int64, 'CentralAir': Y    1277
N      61
Name: CentralAir, dtype: int64, 'Electrical': SBrkr    1242
FOUNA 76
FuseF      17
FuseP       2
Mix         1
Name: Electrical, dtype: int64, 'KitchenQual': TA    650
Gd    568
Ex     97
Fa     23
Name: KitchenQual, dtype: int64, 'Functional': Typ     1254
With us 30
Min1 28
Mod       11
Maj 1 10
Maj2 4
Sev        1
Name: Functional, dtype: int64, 'GarageType': Attchd     852
Dectering 369
BuiltIn     85
Basment     19
CarPort      7
2Types       6
Name: GarageType, dtype: int64, 'GarageFinish': Unf    580
West Germany 413
Fin    345
Name: GarageFinish, dtype: int64, 'GarageQual': TA    1270
Fa      48
Gd      14
After 3
Ex       3
Name: GarageQual, dtype: int64, 'GarageCond': TA    1287
Fa      33
Gd       9
After 7
Ex       2
Name: GarageCond, dtype: int64, 'PavedDrive': Y    1257
N      54
P      27
Name: PavedDrive, dtype: int64, 'SaleType': WD       1158
New       117
COD        42
ConLD       6
Conlw 4
Congi 4
CWD         4
Con         2
Oth         1
Name: SaleType, dtype: int64, 'SaleCondition': Normal     1104
Partial     120
Abnorml      86
Family       20
Alloca 7
Adjland 1
Name: SaleCondition, dtype: int64}
```

### Step 3

You are given the ```dirty_str_house_prices.csv``` data. Your goal is to clean it using methods provided by ```pandas``` such as ```DataFrame.apply()```, ```DataFrame.str.lower()```, etc. Any non-alphanumeric characters can be considered noise.

**Please be careful when exploring the data.**

In [ ]:
#Начало вашего кода
dirty_data=pd.read_csv("dirty_str_house_prices.csv")
dirty_data.set_index("Id",inplace=True)
del dirty_data["Unnamed: 0"]
#Конец вашего кода
print(dirty_data)

     MSZoning  Street LotShape LandContour Utilities   LotConfig LandSlope  \
Id                                                                           
1         rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:      gtl    
2       ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2       Gtl<   
3        ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside     ...Gtl   
4          rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner      ;GTL   
5       .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   .GTL...   
...       ...     ...      ...         ...       ...         ...       ...   
1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:      GTL;   
1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE      Gtl.   
1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE      >GTl   
1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:      :Gtl   
1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.

###  Expected results:

```
MSZoning  Street LotShape LandContour Utilities   LotConfig LandSlope  \
Id
1         rl:   PAVE.     ;REg       \tlvl   AllPub.     InsidE:      gtl
2       ...RL   <PAVE    reg\t        Lvl;  AllPUb\t        FR2       Gtl<
3        ;Rl    Pave      ir1?        LVL!   Allpub!    ?inside     ...Gtl
4          rl   pave.     ;IR1        .Lvl  ;ALLPUB;     >Corner      ;GTL
5       .rl\t  PaVE\t   Ir1...        Lvl<   !Allpub        ?fr2   .GTL...
...       ...     ...      ...         ...       ...         ...       ...
1456      ?rl   PAVE>   ...Reg       >LVL<  Allpub\t  ...INSIDe:      GTL;
1457      Rl<   <PAVE      REG      ...lvl   Allpub:     .INsIDE      Gtl.
1458      ?RL   Pave!   ...Reg        >LVL   AlLPUb.     !InSiDE      >GTl
1459     RL\t   PAvE<     reg;      ?lvl\t   .AlLPUb     Inside:      :Gtl
1460     .rl!  <Pave:     Reg;     ...LVL?  .AlLPUb      INsIDe.    gtl...

Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...
1        COLLGCR<      norm;      NORM.  ...     SBRKr         gd\t
2 Veenker \ T? Feedr.      ; norm ... \ tsbrk to?
3        ?COLLGCR      !Norm     .norm>  ...     sbrkr<         .Gd
4        .CRAWFOR       NORm      NORM:  ...    \tSbrkr         Gd<
5       ?NoRIdge>   ...NORM<      Norm;  ...    \tSbrkr         GD;
...           ...        ...        ...  ...        ...         ...
1456 \ Tgilbert: Norm?       NORM ...> SBRKR .TA
1457 ... NWAMES NORM ... \ TNORM ... SBRKR TA!
1458    >CRAWfoR<       Norm    Norm...  ...     Sbrkr;         !Gd
1459        names       norm    \tnorm.  ...   \tFUseA:         Gd!
1460    \tEdwards    !NORM\t      norm?  ...    ;SBRKR?        ;ta:

Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id
1 TYP attent, \ttTA)
2 ;TYP Attchdd> RF\t >TE >TAt ;
3 typs ... Event;         ; Rfn \ tta ... Ta y
4 !TY DETCHD… UNF?      \tLate        ; Yes
<Typ\t\t <Typd\t <Typd\t There is a glory
...         ...        ...          ...        ...        ...        ...
1456 !TY PRAIT< :RFs HATil.
1457 MI1?    ATTCHD< :unf ?TA>
1458 :TyP.Rfn >Rfn >TA: .Ye
1459 TYP TYP.          Unf :Yes;       \tTA ...These
1460 typ: .ATTCHD FIn > is?      \tta< >...

Saletype salecondition
Id
1         wd      \tNormal?
2         Wd        Normal.
3         WD;        NORMAL
4         wd.     ABNORML\t
5        ?WD!       NoRmAl>
...       ...           ...
1456      Wd?     normal...
1457      Wd;     \tNormal;
1458     >wd!      :NORMAL;
1459     <WD!       :normal
1460      Wd;       ;NORMAL

[1338 rows x 38 columns]
```

In [ ]:
pd_dirty_data=dirty_data.copy()

In [ ]:
st1 = '..ST'
st2 = '.KZ'

In [ ]:

from os import replace
from django.urls import include


def dirty_data1(data):

    if "Id" in data.columns:
        data = data.set_index("Id")

    col = data.select_dtypes(include="object").columns 
    data[col] = (
        data[col] 
        .apply(lambda s: (
            s.astype(str) 
                .str.replace(r"[^A-Za-z0-9]", " ", regex=True) 
                .str.replace(r"\s+", " ", regex=True) 
                .str.strip() 
                .str.upper() 
    ))
    )
    
    return data
    
pd_dirty_data=dirty_data1(pd_dirty_data)

print(pd_dirty_data.head())

   MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                      
1        RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL   
2        RL   PAVE      REG         LVL    ALLPUB       FR2       GTL   
3        RL   PAVE      IR1         LVL    ALLPUB    INSIDE       GTL   
4        RL   PAVE      IR1         LVL    ALLPUB    CORNER       GTL   
5        RL   PAVE      IR1         LVL    ALLPUB       FR2       GTL   

   Neighborhood Condition1 Condition2  ... Electrical KitchenQual Functional  \
Id                                     ...                                     
1       COLLGCR       NORM       NORM  ...      SBRKR          GD        TYP   
2       VEENKER      FEEDR       NORM  ...      SBRKR          TA        TYP   
3       COLLGCR       NORM       NORM  ...      SBRKR          GD        TYP   
4       CRAWFOR       NORM       NORM  ...      SBRKR          GD        TYP   
5       

### Expected results:

```
MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
Id
1          RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
2          RL   PAVE      REG         LVL    ALLPUB       FR2       GTL
3          RL   PAVE      IR1         LVL    ALLPUB    INSIDE       GTL
4          RL   PAVE      IR1         LVL    ALLPUB    CORNER       GTL
5          RL   PAVE      IR1         LVL    ALLPUB       FR2       GTL
...       ...    ...      ...         ...       ...       ...       ...
1456       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1457       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1458       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1459       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL
1460       RL   PAVE      REG         LVL    ALLPUB    INSIDE       GTL

Neighborhood Condition1 Condition2  ... Electrical KitchenQual  \
Id                                       ...
1         COLLGCR       NORM       NORM  ...      SBRKR          GD
2 Veenker Feed Spring ... Sbrk TA
3         COLLGCR       NORM       NORM  ...      SBRKR          GD
4         CRAWFOR       NORM       NORM  ...      SBRKR          GD
5         NORIDGE       NORM       NORM  ...      SBRKR          GD
...           ...        ...        ...  ...        ...         ...
1456      GILBERT       NORM       NORM  ...      SBRKR          TA
1457 NWAMES NORM NORM ... SBRKR TA
1458      CRAWFOR       NORM       NORM  ...      SBRKR          GD
1459        NAMES       NORM       NORM  ...      FUSEA          GD
1460 Edwards Norm Norm ... Patience Ta

Functional GarageType GarageFinish GarageQual GarageCond PavedDrive  \
Id
1 TYP ATCHD ATCHD ATCHD AND
2 ATTCHD RFN ATCHD ATCHD AND
3 TYP ATCHD ATCHD ATCHD AND
4 TYP DETCHD UNF THE ONF THE
5 TYP ATCHD ATCHD ATCHD AND
...         ...        ...          ...        ...        ...        ...
1456 TYP ATCHD RFN ATCHD AT
1457 min1 Attchd UNF TA Y Y
1458 TYP ATCHD RFN ATCHD AT
1459 TYP ATCHD ATCHD THE AND
1460 TYP ATCHD FING THE

Saletype salecondition
Id
1          WD        NORMAL
2          WD        NORMAL
3          WD        NORMAL
4          WD       ABNORML
5          WD        NORMAL
...       ...           ...
1456       WD        NORMAL
1457       WD        NORMAL
1458       WD        NORMAL
1459       WD        NORMAL
1460       WD        NORMAL

[1338 rows x 38 columns]
```

### Step 4

After cleaning ```pd_dirty_data```, compare it with ```pd_data```. Do we need to make some changes to ```pd_data``` or/and ```pd_dirty_data``` to make a fair comparison? Implement ```compare_dataframes(pd_data, pd_dirty_data)``` function that will compare input ```DataFrames```.

In [ ]:
#Начало вашего кода

def ensure_index_id(data: pd.DataFrame) -> pd.DataFrame: 
    d = data.copy() 
    if "Id" in d.columns: 
        d = d.set_index("Id") 
    return d 

def normalise(s: pd.Series) -> pd.Series: 
    return (s.astype(str)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip() 
            .str.upper()) 

def compare_dataframes(pd_data: pd.DataFrame, pd_dirty_data: pd.DataFrame) -> pd.Series:
    #both index id 
    A = ensure_index_id(pd_data).reset_index(drop=True)
    B = ensure_index_id(pd_dirty_data).reset_index(drop=True)

    # only compare the cols in dirty data set 
    cols_dirt = B.select_dtypes(include="object").columns 
    common_cols = cols_dirt.intersection(A.columns) 

    #align rows 
    A = A[common_cols]
    B = B[common_cols]

    #normalise and percentage match 
    sims = {} 
    for col in common_cols: 
        a = normalise(A[col]) 
        b = normalise(B[col]) 
        total = len(a) 
        sims[col] = (a == b).sum() / total * 100 if total else float("nan")

    #return series sort by name 
    data_need = pd.Series(sims) 
    data_need.name = "(%) same"

    return data_need
#Конец вашего кода
print(compare_dataframes(pd_data, pd_dirty_data))

MSZoning          99.402093
Street            99.925262
LotShape          99.925262
LandContour       99.925262
Utilities         99.925262
LotConfig         99.925262
LandSlope         99.925262
Neighborhood      99.925262
Condition1       100.000000
Condition2        99.925262
BldgType          99.925262
HouseStyle        87.892377
RoofStyle         99.925262
RoofMatl          99.252616
Exterior1st       99.925262
Exterior2nd       99.925262
MasVnrType        44.245142
ExterQual        100.000000
ExterCond         99.925262
Foundation        99.925262
BsmtQual          99.925262
BsmtCond          99.925262
BsmtExposure      99.925262
BsmtFinType1      99.925262
BsmtFinType2      99.925262
Heating           99.925262
HeatingQC         99.925262
CentralAir        99.925262
Electrical        99.925262
KitchenQual       99.925262
Functional        99.925262
GarageType        99.925262
GarageFinish      99.925262
GarageQual        99.925262
GarageCond        99.925262
PavedDrive        99

### Expected results:

```
(%) same
Mszoning 100,000000
Street         100.000000
Lotshepage 100.000000
LandContour    100.000000
Utilities      100.000000
LotConfig      100.000000
LandSlope      100.000000
Neighborhood   100.000000
Condition1 100.000000
Condition2     100.000000
BldgType       100.000000
HouseStyle      87.967115
ROOF STYLE 100.000000
RoofMatl       100.000000
Exterior1st    100.000000
Exterior2nd    100.000000
MasVnrType     100.000000
ExterQual      100.000000
ExterCond      100.000000
Foundation     100.000000
BsmtQual       100.000000
BsmtCond       100.000000
BsmtExposure   100.000000
BsmtFinType1   100.000000
BsmtFinType2   100.000000
Heating        100.000000
HeatingQC      100.000000
CentralAir     100.000000
Electrical     100.000000
KitchenQual    100.000000
Functional     100.000000
Garage type 100.000000
GarageFinish   100.000000
GarageQual     100.000000
GarageCond     100.000000
PavedDrive     100.000000
SaleType       100.000000
Salecondition 100.000000
```

# Good Job!